# -*- coding: utf-8 -*-
"""CC embed merge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAj6AYxuWMZdKOU570c1W_EctvCI9UHf
"""

import pandas as pd

embedding_csv = "/content/drive/MyDrive/research/averaged_complaint_embeddings.csv"
df_embeddings = pd.read_csv(embedding_csv)

if "cleaned_complaint" in df_embeddings.columns:
    df_embeddings = df_embeddings.drop(columns=["cleaned_complaint"])
if "chief_complaint" in df_embeddings.columns:
    df_embeddings = df_embeddings.drop(columns=["chief_complaint"])


existing_data_csv = "/content/drive/MyDrive/research/physical_icd_medfreq-3.csv"
df_existing = pd.read_csv(existing_data_csv)


df_merged = pd.merge(df_existing, df_embeddings, on=["subject_id", "hadm_id"], how="left")
df_merged = df_merged.fillna(0.0)

df_merged.to_csv("/content/drive/MyDrive/research/phy_icd_medfreq_CCembed.csv", index=False)