# -*- coding: utf-8 -*-
"""diagnosis ICD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAj6AYxuWMZdKOU570c1W_EctvCI9UHf
"""

import pandas as pd
import gc


df_phy = pd.read_csv("/content/PhysicalandAdmission-2.csv")
los_col = 'LOS'
mean_los = df_phy[los_col].mean()
std_los = df_phy[los_col].std()
threshold = mean_los + 2 * std_los
df_phy = df_phy[df_phy[los_col] >= threshold]
print(f"Filtered LOS threshold: {threshold}, rows: {len(df_phy)}")

usecols = ['subject_id', 'hadm_id', 'icd_code', 'icd_version']
df_icd = pd.read_csv("/content/diagnoses_icd.csv", usecols=usecols)

# get only icd version 10
df_icd = df_icd[df_icd['icd_version'] != 9]
df_icd = df_icd[df_icd['subject_id'].isin(df_phy['subject_id'])]
print(f"Filtered ICD rows: {len(df_icd)}")


df_icd['value'] = 1
df_icd['icd_code'] = df_icd['icd_code'].astype('category')
df_icd['subject_id'] = df_icd['subject_id'].astype('int32')
df_icd['hadm_id'] = df_icd['hadm_id'].astype('int32')


gc.collect()

# pivot table by subject_id + hadm_id
df_encoded = df_icd.pivot_table(
    index=['subject_id', 'hadm_id'],
    columns='icd_code',
    values='value',
    aggfunc='max',
    fill_value=0,
    observed=True
)


df_encoded.columns = ['d_' + str(c) for c in df_encoded.columns]
df_encoded = df_encoded.reset_index()
print(f"ICD-encoded shape: {df_encoded.shape}")

gc.collect()


merged_df = pd.merge(df_phy, df_encoded, on=['subject_id', 'hadm_id'], how='left')
merged_df = merged_df.fillna(0)
print(f"Merged final shape: {merged_df.shape}")


merged_df.to_csv("/content/phy_dicd.csv", index=False)