# -*- coding: utf-8 -*-
"""hpi embed merge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAj6AYxuWMZdKOU570c1W_EctvCI9UHf
"""

import pandas as pd


existing_data_csv = "/content/drive/MyDrive/research/physical_icd_medfreq-3.csv"
df_existing = pd.read_csv(existing_data_csv)


cc_embed_csv = "/content/drive/MyDrive/research/averaged_complaint_embeddings_cuml.csv"
df_cc = pd.read_csv(cc_embed_csv)


df_cc = df_cc.drop(columns=[c for c in ["chief_complaint", "cleaned_complaint"] if c in df_cc.columns])


hpi_embed_csv = "/content/drive/MyDrive/research/averaged_hpi_embeddings.csv"
df_hpi = pd.read_csv(hpi_embed_csv)


df_hpi = df_hpi.drop(columns=[c for c in ["hpi", "cleaned_hpi"] if c in df_hpi.columns])

# merge both files
df_merged = pd.merge(df_existing, df_cc, on=["subject_id", "hadm_id"], how="left")
df_merged = pd.merge(df_merged, df_hpi, on=["subject_id", "hadm_id"], how="left")


df_merged = df_merged.fillna(0.0)


df_merged.to_csv("/content/drive/MyDrive/research/phy_icd_medfreq_CCembed_hpiembed_cuml.csv", index=False)