# -*- coding: utf-8 -*-
"""random

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oakFr7cwmRt9c0V9HzxKe_2sxAZK4Iu3
"""

import pandas as pd


df_phyad_dicd = pd.read_csv("/content/drive/MyDrive/research/phyad_dicd.csv")
df_proc = pd.read_csv("/content/procedures_icd.csv")

# --- Keep ICD 10 only ---
df_proc = df_proc[df_proc["icd_version"] != 9][["subject_id","hadm_id","icd_code"]].copy()

# --- Keep only row only in long length ---
keep_keys_proc = df_phyad_dicd[["subject_id","hadm_id"]].drop_duplicates()
df_proc = df_proc.merge(keep_keys_proc, on=["subject_id","hadm_id"], how="inner")

df_proc["icd_code"] = df_proc["icd_code"].astype(str).str.upper().str.strip()
df_proc = df_proc.drop_duplicates(subset=["subject_id","hadm_id","icd_code"])

print("Filtered procedures rows:", len(df_proc))
print("Unique procedure codes:", df_proc['icd_code'].nunique())


p_dummies = pd.get_dummies(df_proc["icd_code"], prefix="p", dtype="uint8")


proc_block = pd.concat([df_proc[["subject_id","hadm_id"]].reset_index(drop=True), p_dummies], axis=1)
df_proc_encoded = proc_block.groupby(["subject_id","hadm_id"], sort=False).max().reset_index()

print("Procedures one hot encoded shape:", df_proc_encoded.shape)


merged_df = df_phyad_dicd.merge(df_proc_encoded, on=["subject_id","hadm_id"], how="left")


p_cols = [c for c in merged_df.columns if c.startswith("p_")]
if p_cols:
    merged_df[p_cols] = merged_df[p_cols].fillna(0).astype("uint8")

print("\nFinal merged dataset with diagnoses + procedures:")
print("Shape:", merged_df.shape)
print(merged_df.head())

merged_df.to_csv("/content/drive/MyDrive/research/phyad_dicd_picd.csv", index=False)