# -*- coding: utf-8 -*-
"""random

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oakFr7cwmRt9c0V9HzxKe_2sxAZK4Iu3
"""

import pandas as pd

df_phy = pd.read_csv("/content/drive/MyDrive/research/phy_ad_drop.csv")
df_icd = pd.read_csv("/content/diagnoses_icd.csv")

# --- ICD 10 ---
df_icd = df_icd[df_icd["icd_version"] != 9].copy()
df_icd.to_csv("dicd_justv10.csv", index=False)

# --- Keep only rows that are long length ---
keep_keys = df_phy[["subject_id","hadm_id"]].drop_duplicates()
df_icd = df_icd.merge(keep_keys, on=["subject_id","hadm_id"], how="inner")

df_icd["icd_code"] = df_icd["icd_code"].astype(str).str.upper().str.strip()
df_icd = df_icd.drop_duplicates(subset=["subject_id","hadm_id","icd_code"])

# ---------- One hot----------
dummies = pd.get_dummies(
    df_icd["icd_code"],
    prefix="d",
    dtype="uint8"
)

icd_sparse = pd.concat([df_icd[["subject_id","hadm_id"]].reset_index(drop=True), dummies], axis=1)
df_icd_encoded = icd_sparse.groupby(["subject_id","hadm_id"], sort=False).max()


df_icd_encoded = df_icd_encoded.reset_index()

print("\nOne-hot encoded ICD shape (sparse dummies):", df_icd_encoded.shape)

# ---------- Merge ----------
merged_df = pd.merge(df_phy, df_icd_encoded, on=['subject_id','hadm_id'], how='left')


d_cols = [c for c in merged_df.columns if c.startswith('d_')]
if d_cols:
    merged_df[d_cols] = merged_df[d_cols].fillna(0).astype('uint8')

print("\nFinal merged shape:", merged_df.shape)
print("Sample of final dataset:")
print(merged_df.head())

merged_df.to_csv("/content/drive/MyDrive/research/phyad_dicd.csv", index=False)