# -*- coding: utf-8 -*-
"""random

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oakFr7cwmRt9c0V9HzxKe_2sxAZK4Iu3
"""

import pandas as pd
import gc


df_phy = pd.read_csv("/content/drive/MyDrive/research/phy_ad.csv")
los_col = 'LOS'
los_mean = df_phy_ad['LOS'].mean()
print("los mean:", los_mean)
los_std_sample = df_phy_ad['LOS'].std()
print("mean + 1 std:", los_std_sample)
los_std = df_phy_ad['LOS'].std() + los_mean
print("mean + 1 std:", los_std)
los_2std = 2 * df_phy_ad['LOS'].std() + los_mean
print("mean + 2 std:", los_2std)

print("dropping everything below:", los_2std)
df_phy = df_phy[df_phy[los_col] >= los_2std]


df_phy.to_csv("/content/drive/MyDrive/research/phy_ad_drop.csv", index = False)