# -*- coding: utf-8 -*-
"""Preprocessing of MIMIC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TYkkyy-CRkgsHudXm0oVwYg7VReXouFd

Pre-processing of MIMIC

# Physical characteristic extraction and remove LOS anythng >500
"""

import pandas as pd
import numpy as np

ad_df = pd.read_csv("/content/admissions.csv")
pt_df = pd.read_csv("/content/patients.csv")
cols = ["subject_id","hadm_id","admission_type","marital_status","race","admittime","dischtime"]
df_phy_ad = ad_df[cols]
df_phy_ad = pd.merge(df_phy_ad,pt_df[["subject_id","gender","anchor_age"]], on = ["subject_id"], how="outer")
#calculating LOS and appending LOS row
df_phy_ad['admittime'] = pd.to_datetime(df_phy_ad['admittime'])
df_phy_ad['dischtime'] = pd.to_datetime(df_phy_ad['dischtime'])
df_phy_ad = df_phy_ad.dropna(subset=["admittime","dischtime"]).copy()
df_phy_ad["LOS"] = round((df_phy_ad['dischtime'] - df_phy_ad['admittime']).dt.total_seconds() / (3600*24),6)
#binary/numeric represenation mapping
gender_nums = {"F":1,"M":2,"nan":0}
race_nums = {'WHITE':1, 'OTHER':2, 'BLACK/AFRICAN AMERICAN':3, 'UNABLE TO OBTAIN':4, 'UNKNOWN':5,
 'WHITE - RUSSIAN':6, 'BLACK/CAPE VERDEAN':7,
 'NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER':8, 'PORTUGUESE':9,
 'WHITE - OTHER EUROPEAN':10, 'HISPANIC/LATINO - PUERTO RICAN':11, 'ASIAN':12,
 'ASIAN - CHINESE':13, 'HISPANIC/LATINO - DOMINICAN':14,
 'HISPANIC/LATINO - SALVADORAN':15, 'BLACK/AFRICAN':16,
 'HISPANIC/LATINO - GUATEMALAN':17, 'ASIAN - SOUTH EAST ASIAN':18,
 'WHITE - BRAZILIAN':19, 'SOUTH AMERICAN':20, 'HISPANIC OR LATINO':21,
 'ASIAN - KOREAN':22, 'BLACK/CARIBBEAN ISLAND':23, 'HISPANIC/LATINO - MEXICAN':24,
 'PATIENT DECLINED TO ANSWER':25, 'HISPANIC/LATINO - CUBAN':26,
 'AMERICAN INDIAN/ALASKA NATIVE':27, 'MULTIPLE RACE/ETHNICITY':28,
 'WHITE - EASTERN EUROPEAN':29, 'HISPANIC/LATINO - HONDURAN':30,
 'HISPANIC/LATINO - CENTRAL AMERICAN':31, 'ASIAN - ASIAN INDIAN':32,
 'HISPANIC/LATINO - COLUMBIAN':33,"nan":0 }
marital_nums = {'WIDOWED':1,'SINGLE':2, 'MARRIED':3, 'DIVORCED':4, "nan":5}
admission_nums = {'URGENT':1, 'EW EMER.':2,'EU OBSERVATION':3, 'OBSERVATION ADMIT':4,
 'SURGICAL SAME DAY ADMISSION':5, 'AMBULATORY OBSERVATION':6, 'DIRECT EMER.':7,
 'DIRECT OBSERVATION':8, 'ELECTIVE':9, "nan":0}
 #mapping values
df_phy_ad["admission_type"] = df_phy_ad["admission_type"].map(admission_nums)
df_phy_ad["admission_type"] = df_phy_ad["admission_type"].fillna(0)
df_phy_ad["marital_status"] = df_phy_ad["marital_status"].map(marital_nums)
df_phy_ad["marital_status"] = df_phy_ad["marital_status"].fillna(0)
df_phy_ad["race"] = df_phy_ad["race"].map(race_nums)
df_phy_ad["race"] = df_phy_ad["race"].fillna(0)
df_phy_ad["gender"] = df_phy_ad["gender"].map(gender_nums)
df_phy_ad["gender"] = df_phy_ad["gender"].fillna(0)
df_phy_ad["LOS"] = df_phy_ad["LOS"].fillna(0)
condition = (df_phy_ad["LOS"] >= 0) & (df_phy_ad["LOS"] <= 500)
df_phy_ad = df_phy_ad[condition]
unique_ids = "Unique number of Subject_Ids: " + str(len(df_phy_ad["subject_id"].unique()))
print(unique_ids)

df_phy_ad.to_csv("/content/drive/MyDrive/research/phy_ad.csv", index = False)
print(df_phy_ad)

"""#dropping for Long Length of Stay Patients"""

import pandas as pd
import gc


df_phy = pd.read_csv("/content/drive/MyDrive/research/phy_ad.csv")
los_col = 'LOS'
los_mean = df_phy_ad['LOS'].mean()
print("los mean:", los_mean)
los_std_sample = df_phy_ad['LOS'].std()
print("mean + 1 std:", los_std_sample)
los_std = df_phy_ad['LOS'].std() + los_mean
print("mean + 1 std:", los_std)
los_2std = 2 * df_phy_ad['LOS'].std() + los_mean
print("mean + 2 std:", los_2std)

print("dropping everything below:", los_2std)
df_phy = df_phy[df_phy[los_col] >= los_2std]


df_phy.to_csv("/content/drive/MyDrive/research/phy_ad_drop.csv", index = False)

"""# Diagnosis icd one hot encoded with physcial characteristics"""

import pandas as pd

df_phy = pd.read_csv("/content/drive/MyDrive/research/phy_ad_drop.csv")
df_icd = pd.read_csv("/content/diagnoses_icd.csv")

# keep only ICD version 10
df_icd = df_icd[df_icd["icd_version"] != 9].copy()
df_icd.to_csv("dicd_justv10.csv", index=False)

# keeping only ICD rows that match subject_id & hadm_id in df_phy
keep_keys = df_phy[["subject_id","hadm_id"]].drop_duplicates()
df_icd = df_icd.merge(keep_keys, on=["subject_id","hadm_id"], how="inner")

df_icd["icd_code"] = df_icd["icd_code"].astype(str).str.upper().str.strip()
df_icd = df_icd.drop_duplicates(subset=["subject_id","hadm_id","icd_code"])

# one hot encoding of icd
dummies = pd.get_dummies(
    df_icd["icd_code"],
    prefix="d",
    dtype="uint8"
)

icd_sparse = pd.concat([df_icd[["subject_id","hadm_id"]].reset_index(drop=True), dummies], axis=1)
df_icd_encoded = icd_sparse.groupby(["subject_id","hadm_id"], sort=False).max()

df_icd_encoded = df_icd_encoded.reset_index()

print("\nOne-hot encoded ICD shape (sparse dummies):", df_icd_encoded.shape)

# merge
merged_df = pd.merge(df_phy, df_icd_encoded, on=['subject_id','hadm_id'], how='left')

d_cols = [c for c in merged_df.columns if c.startswith('d_')]
if d_cols:
    merged_df[d_cols] = merged_df[d_cols].fillna(0).astype('uint8')

print("Final merged shape:", merged_df.shape)
print("Sample of final dataset:")
print(merged_df.head())

merged_df.to_csv("/content/drive/MyDrive/research/phyad_dicd.csv", index=False)

"""#Procedure icd one hot encoded merged with phyiscal characteristics and diagnosis icd"""

import pandas as pd

df_phyad_dicd = pd.read_csv("/content/drive/MyDrive/research/phyad_dicd.csv")
print("Loaded diagnosis-merged dataset:", df_phyad_dicd.shape)

df_proc = pd.read_csv("/content/procedures_icd.csv")

df_proc = df_proc[df_proc["icd_version"] != 9][["subject_id","hadm_id","icd_code"]].copy()


keep_keys_proc = df_phyad_dicd[["subject_id","hadm_id"]].drop_duplicates()
df_proc = df_proc.merge(keep_keys_proc, on=["subject_id","hadm_id"], how="inner")

df_proc["icd_code"] = df_proc["icd_code"].astype(str).str.upper().str.strip()
df_proc = df_proc.drop_duplicates(subset=["subject_id","hadm_id","icd_code"])

print("Filtered procedures rows:", len(df_proc))
print("Unique procedure codes:", df_proc['icd_code'].nunique())

p_dummies = pd.get_dummies(df_proc["icd_code"], prefix="p", dtype="uint8")

proc_block = pd.concat([df_proc[["subject_id","hadm_id"]].reset_index(drop=True), p_dummies], axis=1)
df_proc_encoded = proc_block.groupby(["subject_id","hadm_id"], sort=False).max().reset_index()

print("Procedures one-hot encoded shape:", df_proc_encoded.shape)

merged_df = df_phyad_dicd.merge(df_proc_encoded, on=["subject_id","hadm_id"], how="left")

p_cols = [c for c in merged_df.columns if c.startswith("p_")]
if p_cols:
    merged_df[p_cols] = merged_df[p_cols].fillna(0).astype("uint8")

print("\nFinal merged dataset with diagnoses + procedures:")
print("Shape:", merged_df.shape)
print(merged_df.head())

merged_df.to_csv("/content/drive/MyDrive/research/phyad_dicd_picd.csv", index=False)

print("\nSaved combined dataset to phyad_dicd_picd.csv")

"""# medication frequency"""

import pandas as pd
import re

df = pd.read_csv("/content/drive/MyDrive/research/prescriptions.csv")
df_other = pd.read_csv("/content/drive/MyDrive/research/phyad_dicd_picd.csv")
valid_pairs = df_other[['subject_id','hadm_id']].drop_duplicates()
df = df.merge(valid_pairs, on=['subject_id','hadm_id'], how='inner')


# 1
# standardize drug names
df['drug'] = df['drug'].str.upper().str.strip()
df['prod_strength'] = df['prod_strength'].fillna("")

# formats that I want to remove
df['drug'] = df['drug'].str.replace(r"\*(NF|NON-FORMULARY|OB|DC)\*\s*", "", regex=True)
df['drug'] = df['drug'].str.replace(r"\*NON-FORMULARY\*", "", regex=True)
df['drug'] = df['drug'].str.replace(r"\s*\(.*?\)", "", regex=True)
df['drug'] = df['drug'].str.strip()
df['drug'] = df['drug'].str.replace(r"\s*\d+(\.\d+)?\s*%$", "", regex=True).str.strip()
df['drug'] = df['drug'].str.replace(r"^\s*\d+(\.\d+)?\s*%\.?\s*", "", regex=True)
print(df.head())
print("unique", df['prod_strength'].unique().tolist())


# 2 striping formulas
form_keywords = [
    "TABLET", "CAPSULE", "INJECTION", "ORAL SOLUTION", "SOLUTION", "SUSPENSION",
    "SYRINGE", "VIAL", "PATCH", "BAG", "SPRAY", "CREAM", "OINTMENT", "SUPPOSITORY",
    "DROPPER", "DISKUS", "DEVICE", "LOZENGE", "TUBE", "ELIXIR", "LIQUID", "NEBULIZER"
]

def strip_formulations(drug):
    if not isinstance(drug, str):
        return "UNKNOWN"
    drug = drug.upper()
    for form in form_keywords:
        drug = drug.replace(form, "")
    return drug.strip()

df['drug'] = df['drug'].apply(strip_formulations)

# 3 fixing abbreviations
corrections = {
    "ABACAV": "ABACAVIR",
    "POTASSIUM CHL": "POTASSIUM CHLORIDE",
    "LIDOCAINE" : "LIDOCAINE"
}
df['drug'] = df['drug'].replace(corrections)

# 4
def extract_dose_string(ps):
    if not isinstance(ps, str):
        return "UNKNOWN"
    ps = ps.lower().strip()
    # common dose/unit pattern
    match = re.search(r'(\d+\.?\d*)\s*(mg|mcg|g|gram|grams|ml|mL|iu|units|mEq|%)', ps, re.IGNORECASE)
    if match:
        number = match.group(1)
        unit = match.group(2).replace("grams", "g").replace("gram", "g")
        return f"{number}{unit}".upper()

    match_fraction = re.search(r'(\d+\.?\d*)\s*/\s*(\d+\.?\d*)\s*(mg|mcg|ml|mL|units)', ps, re.IGNORECASE)
    if match_fraction:
        return f"{match_fraction.group(1)}/{match_fraction.group(2)}{match_fraction.group(3)}".upper()
    return "UNKNOWN"

df['dose'] = df['prod_strength'].apply(extract_dose_string)

# 5 map frequency label and code
def frequency_label(doses):
    try:
        doses = int(float(doses))
        reverse_map = {
            0: "NA",
            1: "OD",
            2: "BID",
            3: "TID",
            4: "QID",
            5: "FID",
            6: "Q4H",
            7: "SID",
            8: "Q3H",
            9: "NID",
            10: "TENID",
            11: "Q2H",
            12: "TWID",
            20: "twentID",
            24: "Q1H"
        }
        return reverse_map.get(doses, "OTHER")
    except:
        return "NA"

def frequency_code(doses):
    try:
        doses = int(float(doses))
        return {
            0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 20: 20, 24: 24
        }.get(doses, 0)
    except:
        return 0

df['frequency'] = df['doses_per_24_hrs'].apply(frequency_label)
df['freq_code'] = df['doses_per_24_hrs'].apply(frequency_code)


#6 drug dose frequency table for statistics purposes
valid_subjects = df_other['subject_id'].unique()
df = df[df['subject_id'].isin(valid_subjects)]

tidy_df = df[['subject_id', 'hadm_id', 'drug', 'dose', 'frequency']].copy()
tidy_df = tidy_df.drop_duplicates(subset=['subject_id','hadm_id','drug','dose','frequency'], keep='first')

tidy_df = tidy_df.sort_values(by=['subject_id', 'hadm_id', 'drug'])
tidy_df.to_csv("tidy_drug_dose_frequency_table_new.csv", index=False)

df = df[df['dose'] != "UNKNOWN"]
df = df[df['drug'].notnull() & (df['drug'] != "")]

df = df[~df['drug'].str.match(r"^\d+|SYRINGES?|LOZENGES?|CUPS?|TUBES?|INHALERS?|BAGS?|SUPPLIES?|^1\s", case=False)]

# med_doselong format with freq_code
df['drug'] = df['drug'].astype(str).str.upper().str.strip()
df['drug'] = df['drug'].str.replace(r"\*NF\*\s*", "", regex=True)
df['med_dose'] = df['drug'] + "_" + df['dose'].str.replace(" ", "")
grouped = df.groupby(['subject_id', 'med_dose']).size().reset_index(name='present')
grouped['present'] = 1
grouped.to_csv("long_med_dose_freq_code_new.csv", index=False)


df['med_dose'] = df['drug'].str.replace(r"\W+", "", regex=True) + "_" + df['dose'].str.replace(" ", "")
grouped = df.groupby(['subject_id', 'hadm_id', 'med_dose']).size().reset_index(name='present')
grouped['present'] = 1

matrix = grouped.pivot(index=['subject_id', 'hadm_id'], columns='med_dose', values='present')\
                .fillna(0).astype(int).reset_index()

matrix.to_csv("medication_one_hot_matrix.csv_new", index=False)
# end of 6


#7 med freq matrix construction
accepted_freqs = ["NA","OD", "BID", "TID", "QID","FID","Q4H","SID","Q3H","NID","TENID","Q2H","TWID","twentID","Q1H"]

freq_map = {
    "NA": 0,
    "OD": 1,
    "BID": 2,
    "TID": 3,
    "QID": 4,
    "FID": 5,
    "Q4H": 6,  # every 4 hours = 6 per 24
    "SID": 7,
    "Q3H": 8,  # every 3 hours = 8 per 24
    "NID": 9,
    "TENID": 10,
    "Q2H": 11, # every 3 hours = 12 per 24hrs
    "TWID": 12,
    "twentID": 20,
    "Q1H": 24, # every hour = 24 per p24
}
def categorize_frequency(value):
    try:
        val = str(value).strip().upper()
        if val in ["", "NA", "N/A", "PLEASE SELECT AN OPTION"]:
            return "NA"
        elif val in accepted_freqs:
            return val
        else:
            return "OTHER"
    except:
        return "NA"
# applying the mapping
df['frequency_clean'] = df['frequency'].apply(categorize_frequency)
df['freq_code'] = df['frequency_clean'].map(freq_map)

df['med_dose'] = df['drug'].str.replace(r"\W+", "", regex=True) + "_" + df['dose'].str.replace(" ", "")
freq_grouped = df.groupby(['subject_id', 'hadm_id', 'med_dose'])['freq_code'].max().reset_index()
freq_matrix = freq_grouped.pivot(index=['subject_id', 'hadm_id'], columns='med_dose', values='freq_code')\
                           .fillna(0).astype(int).reset_index()

freq_matrix.to_csv("/content/drive/MyDrive/research/med_freq_matrix_new.csv", index=False)

df_data = pd.read_csv("/content/drive/MyDrive/research/phyad_dicd_picd.csv")
df_med =  pd.read_csv("/content/drive/MyDrive/research/med_freq_matrix_new.csv")
merged_df = pd.merge(df_data, df_med, on=['subject_id','hadm_id'], how='left')
merged_df = merged_df.fillna(0)
merged_df.to_csv("/content/drive/MyDrive/research/phyad_dicd_picd_medfreq.csv", index=False)

"""#chief complaint extraction"""

import pandas as pd
import re


notes_df = pd.read_csv("/content/drive/MyDrive/research/discharge.csv")
df_other = pd.read_csv("/content/drive/MyDrive/research/phyad_dicd_picd_medfreq.csv")

valid_pairs = df_other[['subject_id','hadm_id']].drop_duplicates()
notes_df = notes_df.merge(valid_pairs, on=['subject_id','hadm_id'], how='inner')


# cc extraction function
# case 1 cc doesn't exist
# case 2 end point doesnt exist so take the next 50 words
# case 3 everything exist so take the section
def extract_chief_complaint(note_text):
    if not isinstance(note_text, str) or not note_text.strip():
        return "NA"

    text = note_text.upper()

    start_match = re.search(r'\b(CHIEF COMPLAINT|CC):?', text)
    if not start_match:
        return "NA"

    start_idx = start_match.end()

    end_match = re.search(r'MAJOR SURGICAL OR INVASIVE PROCEDURE:', text[start_idx:])
    if end_match:
        end_idx = start_idx + end_match.start()         # case 3
        complaint = text[start_idx:end_idx].strip()
    else:
        words = text[start_idx:].strip().split()        # case 2
        complaint = ' '.join(words[:50])


    complaint = re.sub(r'\b(CHIEF COMPLAINT|CC):?', '', complaint).strip()
    return complaint


notes_df['chief_complaint'] = notes_df['text'].apply(extract_chief_complaint)

print("number of unique subjects",notes_df['subject_id'].nunique())

notes_df[['subject_id', 'hadm_id', 'chief_complaint']].to_csv("chief_complaint_extract_new.csv", index=False)

"""#chief complaint cleaning"""

!pip install nltk==3.8.1  # this version works for colab

import nltk
nltk.download('punkt')
nltk.download('stopwords')

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import pandas as pd
import string

import pandas as pd
import nltk
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize


nltk.download('punkt')
nltk.download('stopwords')


df = pd.read_csv("/content/drive/MyDrive/research/chief_complaint_extract_new.csv")
complaints = df["chief_complaint"].astype(str).tolist()


with open("/content/wordlist.txt", "r") as f:
    med_dict = set(line.strip().lower() for line in f if line.strip())


stop_words = set(stopwords.words('english'))


cleaned_complaints = []
total_tokens = 0
total_removed_stopwords = 0
total_removed_nondict = 0
skipped_lines = 0

for line in complaints:
    if pd.isna(line) or not str(line).strip():
        cleaned_complaints.append("")
        skipped_lines += 1
        continue

    tokens = word_tokenize(line.lower())

    tokens = [re.sub(r'\W+', '', t) for t in tokens if t.isalnum()]
    total_tokens += len(tokens)

    # stopwords removal
    tokens_nostop = [t for t in tokens if t not in stop_words]
    total_removed_stopwords += len(tokens) - len(tokens_nostop)

    # med dict filtering
    final_tokens = [t for t in tokens_nostop if t in med_dict]
    total_removed_nondict += len(tokens_nostop) - len(final_tokens)


    cleaned_complaints.append(" ".join(sorted(set(final_tokens))))

df["cleaned_complaint"] = cleaned_complaints


df.to_csv("/content/drive/MyDrive/research/chief_complaint_cleaned_new.csv", index=False)

# statistics
print("=== Cleaning Statistics ===")
print(f"Total original complaints: {len(complaints)}")
print(f"Total cleaned complaints kept: {sum(1 for c in cleaned_complaints if c)}")
print(f"Total complaints skipped (empty or filtered out): {skipped_lines}")
print(f"Total tokens before cleaning: {total_tokens}")
print(f"Total stopwords removed: {total_removed_stopwords}")
print(f"Total tokens removed (not in med dictionary): {total_removed_nondict}")
print(f"Remaining tokens: {sum(len(c.split()) for c in cleaned_complaints if c)}")
print(f"Average tokens per cleaned complaint: {sum(len(c.split()) for c in cleaned_complaints if c) / max(1, (len(cleaned_complaints)-skipped_lines)):.2f}")

"""#chief complaint into txt for embeddings"""

import pandas as pd
from pathlib import Path

df = pd.read_csv("/content/drive/MyDrive/research/chief_complaint_cleaned_new.csv")

mask = df['cleaned_complaint'].notna() & (df['cleaned_complaint'].astype(str).str.strip() != "")
df_nonempty = df.loc[mask, 'cleaned_complaint'].astype(str).str.strip()

df_nonempty = df_nonempty.str.replace(r'\s+', ' ', regex=True)
output_path = Path("/content/cc_new.txt")
df_nonempty.to_csv(output_path, index=False, header=False)

"""#history of present illness extraction"""

import pandas as pd
import re

notes_df = pd.read_csv("/content/drive/MyDrive/research/discharge.csv")
df_other = pd.read_csv("/content/drive/MyDrive/research/phyad_dicd_picd_medfreq.csv")

valid_pairs = df_other[['subject_id','hadm_id']].drop_duplicates()
notes_df = notes_df.merge(valid_pairs, on=['subject_id','hadm_id'], how='inner')

# HPI extraction function
# case 1 hpi section doesn't exist so return NA
# case 2 end point doesn't exist to take next 200 words
# case 3 everything exist so take everything
def extract_hpi(note_text, max_words=200, end_patterns=(r'PAST MEDICAL HISTORY', r'PMH')):
    if not isinstance(note_text, str) or not note_text.strip():
        return "NA"
    start_headers = (
        r'HISTORY OF PRESENT ILLNESS',
        r'HISTORY OF PRESENTING ILLNESS',
        r'HPI',
    )
    start_regex = rf'\b(?:{"|".join(start_headers)})\s*[:\-–—\.]?\s*'

    start = re.search(start_regex, note_text, flags=re.IGNORECASE)
    if not start:
        return "NA"

    start_idx = start.end()
    tail = note_text[start_idx:]

    end_regex = '|'.join(fr'\b{p}\b\s*[:\-–—\.]?\s*' for p in end_patterns)
    m = re.search(end_regex, tail, flags=re.IGNORECASE)
    end_idx = (start_idx + m.start()) if m else None

    if end_idx is not None:
        # case 3
        segment = note_text[start_idx:end_idx]
    else:
        # case 2
        words = re.findall(r'\S+', tail)
        segment = ' '.join(words[:max_words])

    segment = re.sub(start_regex, '', segment, flags=re.IGNORECASE)

    # handling lowercase and whitespace
    segment = re.sub(r'\s+', ' ', segment).strip()
    return segment.lower() if segment else "NA"


notes_df['hpi'] = notes_df['text'].apply(lambda t: extract_hpi(t, max_words=200))

out_path = "/content/drive/MyDrive/research/hpi_extract_new.csv"
notes_df[['subject_id', 'hadm_id', 'hpi']].to_csv(out_path, index=False)

print("Saved:", out_path)
print("Rows written:", len(notes_df))
print("NA rate:", (notes_df['hpi'] == "NA").mean())

"""#history of present illness cleaning"""

import pandas as pd
import nltk
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize


nltk.download('punkt')
nltk.download('stopwords')


df = pd.read_csv("/content/drive/MyDrive/research/hpi_extract_new.csv")
hpis = df["hpi"].astype(str).tolist()

# med dict
with open("/content/wordlist.txt", "r") as f:
    med_dict = set(line.strip().lower() for line in f if line.strip())

stop_words = set(stopwords.words('english'))


cleaned_hpi = []
total_tokens = 0
total_removed_stopwords = 0
total_removed_nondict = 0
skipped_lines = 0

for line in hpis:
    if pd.isna(line) or not str(line).strip() or str(line).strip().upper() == "NA":
        cleaned_hpi.append("")
        skipped_lines += 1
        continue


    tokens = word_tokenize(line.lower())


    tokens = [re.sub(r'\W+', '', t) for t in tokens if t.isalnum()]
    total_tokens += len(tokens)

    # stopwords removal
    tokens_nostop = [t for t in tokens if t not in stop_words]
    total_removed_stopwords += len(tokens) - len(tokens_nostop)

    # keep what is present in the med dict
    final_tokens = [t for t in tokens_nostop if t in med_dict]
    total_removed_nondict += len(tokens_nostop) - len(final_tokens)

    cleaned_hpi.append(" ".join(sorted(set(final_tokens))))


df["cleaned_hpi"] = cleaned_hpi
df["cleaned_hpi"] = df["cleaned_hpi"].fillna("")
df["cleaned_hpi"] = df["cleaned_hpi"].replace(["nan", "NA"], "").fillna("")


out_path = "/content/drive/MyDrive/research/hpi_cleaned_new.csv"
df.to_csv(out_path, index=False)

# stats
print("=== HPI Cleaning Statistics ===")
print(f"Total original HPI rows: {len(hpis)}")
print(f"Total cleaned HPI kept: {sum(1 for c in cleaned_hpi if c)}")
print(f"Total HPI skipped (empty/NA): {skipped_lines}")
print(f"Total tokens before cleaning: {total_tokens}")
print(f"Total stopwords removed: {total_removed_stopwords}")
print(f"Total tokens removed (not in med dictionary): {total_removed_nondict}")
remaining = sum(len(c.split()) for c in cleaned_hpi if c)
print(f"Remaining tokens: {remaining}")
print(f"Average tokens per cleaned HPI: {remaining / max(1, (len(cleaned_hpi)-skipped_lines)):.2f}")
print("Saved:", out_path)

"""#hpi into txt"""

import pandas as pd
from pathlib import Path


df = pd.read_csv("/content/drive/MyDrive/research/hpi_cleaned_new.csv")

mask = df['cleaned_hpi'].notna() & (df['cleaned_hpi'].astype(str).str.strip() != "")
df_nonempty = df.loc[mask, 'cleaned_hpi'].astype(str).str.strip()

df_nonempty = df_nonempty.str.replace(r'\s+', ' ', regex=True)

output_path = Path("/content/hpi_new.txt")
df_nonempty.to_csv(output_path, index=False, header=False)

"""#combing both chief complaint and history present illness txt to feed int word2vec"""

cc_path = "/content/cc_new.txt"
hpi_path = "/content/hpi_new.txt"
out_path = "cc_hpi_new.txt"

with open(cc_path, "r", encoding="utf-8") as f1, open(hpi_path, "r", encoding="utf-8") as f2, open(out_path, "w", encoding="utf-8") as out:
    out.writelines(f1.readlines())
    out.writelines(f2.readlines())

"""#vector averaging of cheif complaint"""

import numpy as np
import pandas as pd


embedding_path = "/content/cc_hpi_embed_new.txt"
embedding_dim = 100
word_vectors = {}

with open(embedding_path, "r", encoding="utf-8") as f:
    for line in f:
        parts = line.strip().split()
        if len(parts) != embedding_dim + 1:
            continue
        word = parts[0]
        vector = np.array(parts[1:], dtype=float)
        word_vectors[word] = vector


csv_path = "/content/drive/MyDrive/research/chief_complaint_cleaned_new.csv"
df = pd.read_csv(csv_path)

complaint_col = "cleaned_complaint"


def average_vector(text, word_vectors, embedding_dim=100):
    if pd.isna(text):
        return np.zeros(embedding_dim)

    tokens = str(text).split()
    vectors = [word_vectors[word] for word in tokens if word in word_vectors]

    if vectors:
        return np.mean(vectors, axis=0)
    else:
        return np.zeros(embedding_dim)

df["embedding"] = df[complaint_col].apply(lambda x: average_vector(x, word_vectors))


embedding_df = pd.DataFrame(df["embedding"].to_list(), index=df.index)
embedding_df.columns = [f"cc_embedding_{i}" for i in range(embedding_dim)]


final_df = pd.concat([df.drop(columns=["embedding"]), embedding_df], axis=1)


final_df.to_csv("/content/drive/MyDrive/research/averaged_cc_embeds_new.csv", index=False)

"""#merging of averaged chief complaint vectors into dataset"""

import pandas as pd


embedding_csv = "/content/drive/MyDrive/research/averaged_cc_embeds_new.csv"
df_embeddings = pd.read_csv(embedding_csv)

if "cleaned_complaint" in df_embeddings.columns:
    df_embeddings = df_embeddings.drop(columns=["cleaned_complaint"])
if "chief_complaint" in df_embeddings.columns:
    df_embeddings = df_embeddings.drop(columns=["chief_complaint"])

existing_data_csv = "/content/drive/MyDrive/research/phyad_dicd_picd_medfreq.csv"
df_existing = pd.read_csv(existing_data_csv)

#merge
df_merged = pd.merge(df_existing, df_embeddings, on=["subject_id", "hadm_id"], how="left")
df_merged = df_merged.fillna(0.0)
df_merged.to_csv("/content/drive/MyDrive/research/phyad_dicd_picd_medfreq_CCembed_new.csv", index=False)

"""#vector averaging of history of present illness

"""

import numpy as np
import pandas as pd


embedding_path = "/content/cc_hpi_embed_new.txt"
embedding_dim = 100
word_vectors = {}

with open(embedding_path, "r", encoding="utf-8") as f:
    for line in f:
        parts = line.strip().split()
        if len(parts) != embedding_dim + 1:
            continue
        word = parts[0]
        vector = np.array(parts[1:], dtype=float)
        word_vectors[word] = vector


csv_path = "/content/drive/MyDrive/research/hpi_cleaned_new.csv"
df = pd.read_csv(csv_path)

complaint_col = "cleaned_hpi"


def average_vector(text, word_vectors, embedding_dim=100):
    if pd.isna(text):
        return np.zeros(embedding_dim)

    tokens = str(text).split()
    vectors = [word_vectors[word] for word in tokens if word in word_vectors]

    if vectors:
        return np.mean(vectors, axis=0)
    else:
        return np.zeros(embedding_dim)

df["embedding"] = df[complaint_col].apply(lambda x: average_vector(x, word_vectors))


embedding_df = pd.DataFrame(df["embedding"].to_list(), index=df.index)
embedding_df.columns = [f"hpi_embedding_{i}" for i in range(embedding_dim)]


final_df = pd.concat([df.drop(columns=["embedding"]), embedding_df], axis=1)

final_df.to_csv("/content/drive/MyDrive/research/averaged_hpi_embed_new.csv", index=False)

"""#merging of history of present illness into dataset"""

import pandas as pd


embedding_csv = "/content/drive/MyDrive/research/averaged_hpi_embed_new.csv"
df_embeddings = pd.read_csv(embedding_csv)

if "hpi" in df_embeddings.columns:
    df_embeddings = df_embeddings.drop(columns=["hpi"])
if "cleaned_hpi" in df_embeddings.columns:
    df_embeddings = df_embeddings.drop(columns=["cleaned_hpi"])

existing_data_csv = "/content/drive/MyDrive/research/phyad_dicd_picd_medfreq_CCembed_new.csv"
df_existing = pd.read_csv(existing_data_csv)

df_merged = pd.merge(df_existing, df_embeddings, on=["subject_id", "hadm_id"], how="left")
df_merged = df_merged.fillna(0.0)

df_merged.to_csv("/content/drive/MyDrive/research/phyad_dicd_picd_medfreq_CCembed_HPIembed_new.csv", index=False)

"""#brief hospital course extraction (not merged with dataset)"""

import pandas as pd
import re


notes_df = pd.read_csv("/content/drive/MyDrive/research/discharge.csv")
df_other = pd.read_csv("/content/drive/MyDrive/research/phyad_dicd_picd_medfreq_CCembed_HPIembed_new.csv")

valid_pairs = df_other[['subject_id','hadm_id']].drop_duplicates()
notes_df = notes_df.merge(valid_pairs, on=['subject_id','hadm_id'], how='inner')

def extract_brief_hospital_course(
    note_text,
    max_words=1000,
    end_patterns=(
        r'MEDICATIONS ON ADMISSION',
    ),
    start_headers=(
        r'BRIEF HOSPITAL COURSE',
        r'HOSPITAL COURSE',
    )
):

    if not isinstance(note_text, str) or not note_text.strip():
        return "NA"

    note_text = note_text.replace("–", "-").replace("—", "-")

    start_regex = rf'\b(?:{"|".join(start_headers)})\b\s*[:\-\.]?\s*'
    start = re.search(start_regex, note_text, flags=re.IGNORECASE)
    if not start:
        return "NA"  # case 1

    start_idx = start.end()
    tail = note_text[start_idx:]

    end_regex = '|'.join(fr'\b{p}\b\s*[:\-\.]?\s*' for p in end_patterns)
    m = re.search(end_regex, tail, flags=re.IGNORECASE)
    end_idx = (start_idx + m.start()) if m else None

    if end_idx is not None:
        segment = note_text[start_idx:end_idx]
    else:
        # no end marker found so take next max words
        words = re.findall(r'\S+', tail)
        segment = ' '.join(words[:max_words])

    segment = re.sub(start_regex, '', segment, flags=re.IGNORECASE)
    segment = re.sub(r'\s+', ' ', segment).strip()
    return segment.lower() if segment else "NA"

notes_df['brief_hospital_course'] = notes_df['text'].apply(
    lambda t: extract_brief_hospital_course(
        t,
        max_words=1000,
        end_patterns=(
            r'MEDICATIONS ON ADMISSION',
            # r'MEDS ON ADMISSION',
            # r'ADMISSION MEDICATIONS',
        )
    )
)

out_path = "/content/drive/MyDrive/research/bhc_extract_new.csv"
notes_df[['subject_id', 'hadm_id', 'brief_hospital_course']].to_csv(out_path, index=False)

print("Saved:", out_path)
print("Rows written:", len(notes_df))
print("NA rate:", (notes_df['brief_hospital_course'] == "NA").mean())

"""#major surgical procedures extraciton (not merged with dataset)"""

import pandas as pd
import re

notes_df = pd.read_csv("/content/drive/MyDrive/research/discharge.csv")
df_other = pd.read_csv("/content/drive/MyDrive/research/phyad_dicd_picd_medfreq.csv")

valid_pairs = df_other[['subject_id','hadm_id']].drop_duplicates()
notes_df = notes_df.merge(valid_pairs, on=['subject_id','hadm_id'], how='inner')

# extraction function
def extract_major_proc(note_text, max_words=10,
                       end_patterns=(r'HISTORY OF PRESENT ILLNESS',
                                     r'HISTORY OF PRESENTING ILLNESS',
                                     r'HPI')):
    if not isinstance(note_text, str) or not note_text.strip():
        return "NA"

    start_headers = (
        r'MAJOR\s+SURGICAL\s+(?:OR|/|AND)\s+INVASIVE\s+PROCEDURE(?:S)?',
    )
    start_regex = rf'\b(?:{"|".join(start_headers)})\b\s*[:\-–—\.]?\s*'

    start = re.search(start_regex, note_text, flags=re.IGNORECASE)
    if not start:
        return "NA"

    start_idx = start.end()
    tail = note_text[start_idx:]

    end_regex = '|'.join(fr'\b{p}\b\s*[:\-–—\.]?\s*' for p in end_patterns)
    m = re.search(end_regex, tail, flags=re.IGNORECASE)
    end_idx = (start_idx + m.start()) if m else None

    if end_idx is not None:
        segment = note_text[start_idx:end_idx]
    else:
        words = re.findall(r'\S+', tail)
        segment = ' '.join(words[:max_words])

    segment = re.sub(start_regex, '', segment, flags=re.IGNORECASE)
    segment = re.sub(r'\s+', ' ', segment).strip()
    return segment.lower() if segment else "NA"

def clean_major_text(s: str) -> str:
    if s == "NA" or not isinstance(s, str):
        return s
    if len(s) > 120:
        return "NA"
    if re.search(r'\bnone\b', s, flags=re.IGNORECASE):
        return "none"
    s = re.sub(r'\b\d+\.(?=\s|$)', ' ', s)
    s = re.sub(r'[_:&()\-\u2022]', ' ', s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s

notes_df['major_surg_or_invasive_proc'] = notes_df['text'].apply(
    lambda t: extract_major_proc(t, max_words=10)
)
notes_df['major_surg_or_invasive_proc_clean'] = notes_df['major_surg_or_invasive_proc'].apply(clean_major_text)

filtered = notes_df.loc[
    notes_df['major_surg_or_invasive_proc_clean'].ne("NA"),
    ['subject_id', 'hadm_id', 'major_surg_or_invasive_proc_clean']
].copy()
filtered = filtered.rename(columns={'major_surg_or_invasive_proc_clean': 'major_surg_or_invasive_proc'})

out_path_major = "/content/drive/MyDrive/research/major_extract_new.csv"
filtered.to_csv(out_path_major, index=False)