# -*- coding: utf-8 -*-
"""procedures ICD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAj6AYxuWMZdKOU570c1W_EctvCI9UHf
"""

import pandas as pd
import gc

df_phy = pd.read_csv("/content/PhysicalandAdmission-2.csv")
df_icd = pd.read_csv("/content/procedures_icd.csv")
df_dicd = pd.read_csv("phy_dicd-2.csv")

# focusing on long length stay
los_col = 'LOS'
std_los = df_phy[los_col].std()
print("std",std_los)
mean = df_phy[los_col].mean()
print("mean",mean)
print(mean + (2*std_los))
print("2 std above mean", mean + (2*std_los))
df_phy = df_phy[df_phy[los_col] >= (mean + (2*std_los))]
print("unqiue",str(len(df_phy["subject_id"].unique())))
print("max_day:",max(df_phy[los_col]))

# only icd 10
df_icd = df_icd[df_icd["icd_version"] != 9]
print("icd_unique:",str(df_icd["icd_version"].value_counts()))
print(df_icd)


df_icd = df_icd[df_icd['subject_id'].isin(df_phy['subject_id'])]
print("len after filtering: ", len(df_icd['subject_id'].unique()))

df_icd['value'] = 1
df_icd['icd_code'] = df_icd['icd_code'].astype('category')
df_icd['subject_id'] = df_icd['subject_id'].astype('int32')
df_icd['hadm_id'] = df_icd['hadm_id'].astype('int32')

gc.collect()

# pivot table for one hot
df_icd_encoded = df_icd.pivot_table(
    index=['subject_id','hadm_id'],
    columns='icd_code',
    values='value',
    aggfunc='max',
    fill_value=0 ,
    observed=True
)


df_icd_encoded.columns = ['p_' + str(col) for col in df_icd_encoded.columns]


df_icd_encoded = df_icd_encoded.reset_index()

print("\nOne-hot encoded ICD shape:", df_icd_encoded.shape)

# merge
merged_df = pd.merge(df_dicd, df_icd_encoded, on=['subject_id','hadm_id'], how='left')
merged_df = merged_df.fillna(0)
print("\nFinal merged shape:", merged_df.shape)
print("Sample of final dataset:")
print(merged_df.head())
merged_df = merged_df.fillna(0)
merged_df.to_csv("/content/allICD.csv", index = False)